# Generated by Django 4.0.4 on 2022-05-11 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the project', max_length=100)),
                ('acronym', models.CharField(help_text='Acronym for the name of the project', max_length=20)),
                ('impact_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('pii/phi', 'PII or PHI')], default=None, help_text='FISMA impact level of the project', max_length=20, null=True)),
                ('location', models.CharField(choices=[('cms_aws', 'CMS AWS Commercial East-West'), ('govcloud', 'CMS AWS GovCloud'), ('azure', 'Microsoft Azure'), ('other', 'Other')], default=None, help_text='Where the project is located', max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('creator', models.ForeignKey(default=None, help_text='User id of the project creator', on_delete=django.db.models.deletion.PROTECT, related_name='projects_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_add_members', 'Can add members'), ('can_delete_members', 'Can delete members')],
            },
        ),
    ]
