# Generated by Django 4.0.4 on 2022-06-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_alter_component_catalog_alter_component_search_terms_and_more'),
        ('projects', '0002_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='components',
            field=models.ManyToManyField(help_text='Components that exist in the project', related_name='used_by_projects', to='components.component'),
        ),
    ]
