# Generated by Django 4.0.4 on 2022-06-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_add_members', 'Can add members'), ('can_delete_members', 'Can delete members'), ('manage_project_users', 'Can manage users on project')]},
        ),
    ]
