# Generated by Django 4.0.5 on 2022-06-29 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options'),
        ('projects', '0003_project_components'),
    ]

    operations = [
    ]
