# Generated by Django 4.0.5 on 2022-07-05 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_alter_catalog_file_name'),
        ('projects', '0004_merge_20220629_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='catalog',
            field=models.ForeignKey(default=None, help_text='Catalog id that this project uses', on_delete=django.db.models.deletion.PROTECT, related_name='projects_catalog', to='catalogs.catalog'),
        ),
    ]
