# Generated by Django 4.0.5 on 2022-07-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_alter_component_component_json_and_more'),
        ('projects', '0005_project_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='components',
            field=models.ManyToManyField(blank=True, help_text='Components that exist in the project', related_name='used_by_projects', to='components.component'),
        ),
    ]
