# Generated by Django 4.0.6 on 2022-08-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_catalog_version_alter_project_impact_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='control_label',
            field=models.CharField(default='AC-01', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='control',
            name='title',
            field=models.CharField(default='Access Control', max_length=124),
            preserve_default=False,
        ),
    ]
