# Generated by Django 4.1 on 2022-08-31 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogs', '0005_catalog_impact_level_catalog_version_controls'),
        ('projects', '0007_projectcontrol_project_catalog_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='catalog_version',
            field=models.CharField(default=None, help_text='The Catalog version, for example ARS 3.1', max_length=32),
        ),
        migrations.AlterField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(help_text='User id of the project creator', on_delete=django.db.models.deletion.PROTECT, related_name='projects_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='impact_level',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], help_text='FISMA impact level of the project', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectcontrol',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_control', to='catalogs.controls'),
        ),
        migrations.AlterField(
            model_name='projectcontrol',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_project', to='projects.project'),
        ),
    ]
