# Generated by Django 4.1.1 on 2022-09-26 20:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_catalog_version_alter_project_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontrol',
            name='disabled_narratives',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
