# Generated by Django 4.1.1 on 2022-09-28 14:06

from django.db import migrations, models


def change_existing_values(apps, schema_editor):
    ProjectControl = apps.get_model('projects', 'ProjectControl')

    for project_control in ProjectControl.objects.filter(status="completed"):
        project_control.status = "complete"
        project_control.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_catalog_version_alter_project_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontrol',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectcontrol',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('incomplete', 'Incomplete'), ('complete', 'Complete'), ('not_applicable', 'Not applicable')], default='not_started', help_text='The Project Control status; completed, incomplete, or not started', max_length=20),
        ),
        migrations.RunPython(change_existing_values),
    ]
