[tool.poetry]
name = "blueprint_api"
version = "0.1.0"
description = ""
authors = [
    "Tom Camp <tom.camp@civicactions.com>"
]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^4.0.4"
psycopg2-binary = "^2.9.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
