# Generated by Django 4.0.5 on 2022-07-13 14:01

import catalogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_alter_catalog_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='file_name',
            field=models.FileField(help_text='Location of static catalog data file', upload_to='', validators=[catalogs.models.validate_catalog]),
        ),
    ]
