# Generated by Django 4.0.5 on 2022-07-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_alter_catalog_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='source',
            field=models.URLField(default='https://raw.githubusercontent.com/usnistgov/oscal-content/main/nist.gov/SP800-53/rev5/json/NIST_SP-800-53_rev5_catalog.json', max_length=500),
        ),
    ]
