# Generated by Django 4.1 on 2022-08-15 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_catalog_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='impact_level',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='moderate', help_text='FISMA impact level of the project', max_length=20),
        ),
        migrations.AddField(
            model_name='catalog',
            name='version',
            field=models.CharField(default='CMS ARS 3.1', max_length=64),
        ),
        migrations.CreateModel(
            name='Controls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(help_text='Catalog control ID, for example ac-1', max_length=12)),
                ('control_label', models.CharField(help_text='Catalog control label, for example AC-01', max_length=12)),
                ('sort_id', models.CharField(help_text='Catalog ID used for sorting, for example ac-01', max_length=12)),
                ('title', models.CharField(help_text='Catalog control title, for example Access Control Policy and Procedures.', max_length=124)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.catalog')),
            ],
        ),
    ]
