# Generated by Django 4.1.1 on 2022-09-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0005_catalog_impact_level_catalog_version_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='version',
            field=models.CharField(choices=[('CMS_ARS_3_1', 'CMS ARS 3.1'), ('CMS_ARS_5_0', 'CMS ARS 5.0')], default='CMS_ARS_3_1', max_length=16),
        ),
    ]
