# Generated by Django 4.1.1 on 2022-09-09 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0006_alter_catalog_version'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='catalog',
            unique_together={('version', 'impact_level')},
        ),
    ]
