# Generated by Django 4.0.4 on 2022-06-09 21:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the component', max_length=100)),
                ('description', models.CharField(help_text='Description of the component', max_length=500)),
                ('type', models.CharField(default=None, help_text='Type category of the component', max_length=100)),
                ('controls', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), help_text='List of controls that the component addresses', size=None)),
                ('component_json', models.JSONField(help_text='OSCAL JSON representation of the component')),
                ('search_terms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), help_text='List of keywords to search for the component', size=None)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('catalog', models.ForeignKey(default=None, help_text='Catalog id that this component applies to', on_delete=django.db.models.deletion.PROTECT, related_name='components_for_catalog', to='catalogs.catalog')),
            ],
        ),
    ]
