# Generated by Django 4.0.5 on 2022-06-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_alter_component_catalog_alter_component_search_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='component_file',
            field=models.FileField(blank=True, help_text='Upload an OSCAL formatted JSON Component file', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='component',
            name='status',
            field=models.IntegerField(choices=[(1, 'System Specific'), (2, 'Public')], default=2),
        ),
        migrations.AlterField(
            model_name='component',
            name='description',
            field=models.CharField(blank=True, help_text='Description of the component', max_length=500),
        ),
    ]
