# Generated by Django 4.0.5 on 2022-06-30 16:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_component_component_file_component_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='component_json',
            field=models.JSONField(blank=True, help_text='OSCAL JSON representation of the component', null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='controls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), blank=True, help_text='List of controls that the component addresses', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='component',
            name='title',
            field=models.CharField(help_text='Name of the component', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='type',
            field=models.CharField(blank=True, help_text='Type category of the component', max_length=100, null=True),
        ),
    ]
