# Generated by Django 4.1.1 on 2022-09-09 15:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_alter_component_component_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='catalog',
        ),
        migrations.AddField(
            model_name='component',
            name='supported_catalog_versions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CMS_ARS_3_1', 'CMS ARS 3.1'), ('CMS_ARS_5_0', 'CMS ARS 5.0')], max_length=16), default=['CMS_ARS_3_1'], help_text='Catalog versions that this component is defined on.', size=None),
            preserve_default=False,
        ),
    ]
