---
name: Lint
on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  lint:
    name: Pylint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Set up python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install poetry
        run: pip install poetry
      - run: poetry config virtualenvs.create false
      - name: Install dependencies
        run: poetry install --no-ansi --no-interaction --no-root
      - name: Run pylint
        run: pylint .